### ISSUE TITLE
Error trying to run SiFit

### ISSUE THREAD

**Issue by jpcartailler** [KChen-lab/SiFit#1]
Greetings,
I downloaded SiFit as per the instructions and tried running a test, using the sample data and parameters:
```
java -jar SiFit.jar -m 20 -n 446 -fp 0.002 -fn 0.2 -iter 10000 -df 1 -ipMat exampleFiles/dataset_20cells.txt
```

Here is what is returned:

```
Run 0
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at SiFit.RunSiFit.main(RunSiFit.java:131)
```

I'm not even sure if this project is still active but I figured I would try. Cheers!

**Comment by pawelqs** [comment]
Hi!

For me it worked correctly. Did you download "exampleFiles/dataset_20cells.txt" from this repo into your working directory? If you only followed the instruction, you possibly get only the SiFit.jar file.
